### ISSUE TITLE
Bug with Control Panel and question

### ISSUE THREAD

**Issue by callmehyunv** [Maplespe/ExplorerBlurMica#22] opened 2023-05-05 17:21 UTC
There's this bug in Windows 11's Control Panel. I'm currently in version 22H2. 

![Screenshot_16](https://user-images.githubusercontent.com/127226553/236524520-612c3734-0352-411a-adbd-07731cd851b4.png)

Also, will there be an update for blur effect on 22H2? I honestly love it more than Acrylic effect!

**Comment by Maplespe** [comment] 2023-05-06 15:29
Are you using the latest version? I've just tested it without any problems.

**Comment by WiseTomCat** [comment] 2023-08-15 08:07
@Maplespe Im a fairly new user of your work and this was something I thought would never be possible but here I am using it thanks to you. I have paired your app with Explorer Patcher and Translucent Flyouts in my windows 11 21H2. 
I seem to be having the same issue here. 
![Screenshot 2023-08-15 134602](https://github.com/Maplespe/ExplorerBlurMica/assets/100816109/dea801de-e3c9-4a66-9dcd-a9de943a1d73)

**Comment by Maplespe** [comment] 2023-08-15 10:35
@WiseTomCat Are you using the latest version?
Also does the problem occur when using this program alone? I need to check if it's a conflict with other software.
Also, please tell me what configuration file you have.

**Comment by WiseTomCat** [comment] 2023-08-15 10:39
@Maplespe  Yes I am using the latest version....i noticed that this issue goes away when acryclic is enabled.....only mica and clear have this bug.
The issue with acrylic for me is that it takes a moment to load upon opening file explorer on my intel 12th gen acer nitro 5. Is this a known bug?

[config]
effect=2
smallBorder=false
showLine=false
darkRibbon=true
clearAddress=true
clearBarBg=true
[light]
r=222
g=222
b=222
a=120
[dark]
r=0
g=0
b=0
a=120

**Comment by Maplespe** [comment] 2023-08-15 10:53
There seems to be no problem with my computer, it is a pristine system. So I suspect it may be due to other software conflicts.

**Comment by WiseTomCat** [comment] 2023-08-15 16:03
thank you...i will look into it more on what might be causing it....I love using it even with the bug present in some of our machines. Also does the Microsoft Runtime Framework have any effect on the UI? I wonder what this tweak of yours is dependent upon....some software like Lively walpaper require latest .Net version whereas older programs like Capture One require the version 6....so I uninstalled the latest Version 7 but still no luck so far.

**Comment by Maplespe** [comment] 2023-08-16 08:07
This program is written in native C++ and does not depend on any libraries, including VC, because my Releases are compiled statically.

**Comment by WiseTomCat** [comment] 2023-08-17 06:58
@Maplespe I can confirm that this has compatibility issue when used with Explorer Patcher. Using these settings fixed it for me but If I want to use Acrylic effect then it is still slow to open and exit. 
![image](https://github.com/Maplespe/ExplorerBlurMica/assets/100816109/cbcc1dc9-ace8-4f88-b504-88d6ba91a8d2)

@callmehyunv I think the issue you are facing has to do with windows deciding not to apply Mica to windows explorer fully.
 I had to change several settings in Explorer Patcher to get the bugs almost completely fixed. It fixed the control panel for me as well in Mica mode.

**Comment by Satanarious** [comment] 2023-08-22 21:08
I have a similar problem, I dont use anything besides ExplorerBlurMica that might cause the problem.
**OS**: Windows 10 Build 19045
**ExplorerBlurMica Version**: 1.0.7
Here is my config:
```ini
[config]
effect=1
smallBorder=false
showLine=false
darkRibbon=true
clearAddress=true
clearBarBg=true
[light]
r=222
g=222
b=222
a=120
[dark]
r=0
g=0
b=0
a=120

```
Here are a few screenshots:
<table>
<tr>
<td><img src="https://github.com/Maplespe/ExplorerBlurMica/assets/42642682/9a9e1542-2bab-4179-bbf3-d8b61cf5fa9f">
<td> <img src="https://github.com/Maplespe/ExplorerBlurMica/assets/42642682/ff62906f-79c5-4111-a70a-ae49921a6982">
</tr>
<tr>
<td><img src="https://github.com/Maplespe/ExplorerBlurMica/assets/42642682/72d47e3f-be9b-4a63-b7ea-81e82015319d">
<td><img src="https://github.com/Maplespe/ExplorerBlurMica/assets/42642682/dec6d891-ff76-48c6-a7b0-ebeb81813e50">
</tr>
</table>

**Comment by Maplespe** [comment] 2023-12-31 16:22
This issue has been resolved in the new version Please check.

**Comment by WiseTomCat** [comment] 2024-01-01 04:07
@Maplespe Happy New Year
 I have daily driving this despite few minor bugs but this latest release has fixed all of them in 23H2.
I am the most happy about the opening and closing animation bug that has been fixed as well.

**Closed** 2024-01-17 17:41 UTC
Labels: question, processed
